#!/usr/bin/env python3
"""s29: stabilizer states over Z_d -- the entropy cone remembers the local dimension (R34).

Z_d qudits: the Weyl-Heisenberg group of Z_d, any d >= 2 (docs/R32_reduction_and_local_dimension.md, section 4.6).
A code is a subgroup C of Z_N^m (here the row space of an integer matrix mod N).  The CSS state
|C> = |C|^{-1/2} sum_{c in C} |c> is a stabilizer state with S(X) = r(X) + r(E \\ X) - r(E), where r(X) = log |proj_X C|.
For N = p^k every logarithm is taken to base p, so all quantities here are integers (bits for N = 2^k, trits for
N = 3^k).

Facts checked exactly (gates G32 / G32b):
  * generalised cube states over Z_N (the s28 generator: rows 1, x_1..x_M on the points e_i, c - e_i, c, 0):
    - the code is free (|C| = N^(M+1));
    - the s28 weights d are units and G diag(d) G^T = 0 mod N, so C^perp = C diag(d);
    - r is identically self-dual and h_S = 2r;
    - contracting the origin gives the configuration <e_i>, <c - e_i>, <c> over Z_N;
  * Lemma 4(G) values on the states (pulled back as in s28):
    - Z_4, t = 2: (LA)_2 = (LB)_2 = -2 bits;
    - Z_8, t = 4: (LA)_4 = -2 bits;
    - Z_9, t = 3: (LA)_3 = -2 trits;
    - Z_4, t = 6: (LA)_6 = -2 bits (--full; the case d = 4, d' = 6 of Theorem 5);
  * the Z_4 cube state: the entropies from its state vector (4^8 amplitudes) equal the formula, and its entropy
    vector in bits is the qubit cube vector (bits) plus the qutrit cube vector (trits).

Sanity tests of Lemma 4(G), not proofs (--lemma-tests): random configurations whose variables are 0 or cyclic
subgroups from a fixed list of points (the J - I vectors and their multiples by non-units).

  python3 scripts/s29_zd_stabilizer.py [--cases 2:4 4:8 3:9 6:4] [--state-vector] [--lemma-tests 2200000] [--out f.npz]
"""
import argparse, itertools, math, os, sys, time
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(HERE, '..'))
import s28_generalized_cubes as g28

CASES = ((2, 4), (4, 8), (3, 9))          # (t, N) certified by G32; (6, 4) is added by --full / G32b


def prime_power(N):
    """(p, k) with N = p^k; raises for other N."""
    for p in range(2, N + 1):
        if N % p == 0:
            k, M = 0, N
            while M % p == 0:
                M //= p; k += 1
            if M != 1:
                raise ValueError(f'{N} is not a prime power')
            return p, k
    raise ValueError(N)


def diag_form(A):
    """nonzero diagonal entries of D = U A V with U, V unimodular over Z (exact; A a list of integer rows)."""
    A = [list(map(int, row)) for row in A]
    m = len(A); n = len(A[0]) if m else 0
    d, k = [], 0
    while k < min(m, n):
        piv = min(((abs(A[i][j]), i, j) for i in range(k, m) for j in range(k, n) if A[i][j]), default=None)
        if piv is None:
            break
        _, i, j = piv
        A[k], A[i] = A[i], A[k]
        for row in A:
            row[k], row[j] = row[j], row[k]
        a = A[k][k]
        clean = True
        for i in range(k + 1, m):
            q = A[i][k] // a
            if q:
                A[i] = [x - q * y for x, y in zip(A[i], A[k])]
            clean = clean and A[i][k] == 0
        for j in range(k + 1, n):
            q = A[k][j] // a
            if q:
                for row in A:
                    row[j] -= q * row[k]
            clean = clean and A[k][j] == 0
        if clean:                         # row k and column k are zero apart from the pivot
            d.append(abs(a)); k += 1
    return d


def vp(x, p):
    e = 0
    while x % p == 0:
        x //= p; e += 1
    return e


def log_image(A, N):
    """log_p |image of the Z_N-linear map with integer matrix A| for N = p^k: sum over the diagonal entries d_i of
    k - min(v_p(d_i), k)."""
    if not len(A) or not len(A[0]):
        return 0
    p, k = prime_power(N)
    return sum(k - min(vp(di, p), k) for di in diag_form(A))


def rank_proj(G, N):
    """r(X) = log_p |proj_X(row space of G mod N)| for all column masks X."""
    m = G.shape[1]
    return np.array([log_image(G[:, [i for i in range(m) if X >> i & 1]].T.tolist(), N) if X else 0
                     for X in range(1 << m)], dtype=np.int64)


def rank_sum(V, N):
    """H(X) = log_p |sum of the cyclic subgroups generated by the columns v_i, i in X| for all masks X."""
    m = V.shape[1]
    return np.array([log_image(V[:, [i for i in range(m) if X >> i & 1]].tolist(), N) if X else 0
                     for X in range(1 << m)], dtype=np.int64)


def witness(t, N):
    """generalised cube state over Z_N: rank function, entropy (all masks, purity built in), h_S and the checks."""
    p, k = prime_power(N)
    G = g28.generator(t)
    m = G.shape[1]; FULL = (1 << m) - 1; M = t + 1
    r = rank_proj(G, N)
    pc = np.array([bin(X).count('1') for X in range(1 << m)], dtype=np.int64)
    r_perp = k * pc + r[FULL ^ np.arange(1 << m)] - r[FULL]          # rank function of C^perp
    S_all = np.where((np.arange(1 << m) > 0) & (np.arange(1 << m) < FULL), r + r[FULL ^ np.arange(1 << m)] - r[FULL], 0)
    single = np.array([S_all[1 << i] for i in range(m)], dtype=np.int64)
    h = S_all + np.array([sum(single[i] for i in range(m) if X >> i & 1) for X in range(1 << m)], dtype=np.int64)
    d = g28.self_dual_weights(t)
    weights = bool(all(math.gcd(int(x), N) == 1 for x in d) and not ((G * d) @ G.T % N).any())
    cfg = rank_sum(g28.configuration(t), N)
    origin = 1 << (m - 1)
    contraction = bool(all(r[T | origin] - r[origin] == cfg[T] for T in range(origin)))
    return dict(t=t, N=N, p=p, k=k, r=r, S_all=S_all, h=h, cfg=cfg, free=bool(r[FULL] == k * (M + 1)), weights=weights,
                self_dual=bool(np.array_equal(r_perp, r)), h2r=bool(np.array_equal(h, 2 * r)), contraction=contraction)


def analyse(t, N):
    """witness facts plus the Lemma 4 values on the configuration and on the state (pulled back as in s28)."""
    W = witness(t, N)
    LA, LB, n = g28.lemma_forms(t)
    S = W['S_all'][1:1 << n]
    W.update(n_visible=n, S=S, cfg_LA=int(LA @ W['cfg']), cfg_LB=int(LB @ W['cfg']),
             FA=int(g28.pullback(LA, n) @ S), FB=int(g28.pullback(LB, n) @ S))
    return W


def state_vector_dev(t=2, N=4):
    """max |S_svd(X) - S_formula(X)| (units of log p) over all cuts of the generalised cube state over Z_N."""
    p, _k = prime_power(N)
    G = g28.generator(t); kk, m = G.shape
    U = np.array(list(itertools.product(range(N), repeat=kk)), dtype=np.int64)
    C = np.unique((U @ G) % N, axis=0)
    psi = np.zeros(N ** m)
    psi[C @ (N ** np.arange(m - 1, -1, -1))] = 1 / math.sqrt(len(C))
    psi = psi.reshape([N] * m)
    W = witness(t, N)
    dev = 0.0
    for X in range(1, (1 << m) - 1):
        cols = [i for i in range(m) if X >> i & 1]; rest = [i for i in range(m) if not X >> i & 1]
        s = np.linalg.svd(np.transpose(psi, cols + rest).reshape(N ** len(cols), -1), compute_uv=False) ** 2
        s = s[s > 1e-14]
        dev = max(dev, abs(float(-(s * np.log(s)).sum() / math.log(p)) - W['S_all'][X]))
    return dev, len(C)


def cube_sum_identity():
    """Z_4 cube entropy (bits) == qubit cube (bits) + qutrit cube (trits), on every mask."""
    S4 = witness(2, 4)['S_all']
    S2 = g28.witness(2, 2)[1]; S3 = g28.witness(2, 3)[1]
    return bool(np.array_equal(S4, S2 + S3))


# ------------------------------------------------------------------ Lemma 4(G) sanity tests
class Group:
    """Z_N^dim with an addition table on element indices."""

    def __init__(self, N, dim):
        self.N, self.dim = N, dim
        self.el = np.array(list(itertools.product(range(N), repeat=dim)), dtype=np.int64)
        self.w = N ** np.arange(dim - 1, -1, -1)
        self.add = ((self.el[:, None, :] + self.el[None, :, :]) % N) @ self.w

    def idx(self, v):
        return int((np.asarray(v, dtype=np.int64) % self.N) @ self.w)

    def plus_cyclic(self, A, v):
        """subgroup A + <v> as a sorted array of element indices."""
        vi = self.idx(v); parts = [A]; cur = A
        while True:
            cur = self.add[cur, vi]
            if cur[0] == 0 or np.array_equal(np.sort(cur), A):
                break
            parts.append(cur)
        return np.unique(np.concatenate(parts))


def point_table(Gr, pts):
    """log_p |sum of <v>, v in S| for every subset S of the point list (incremental closure)."""
    p, _k = prime_power(Gr.N)
    P = len(pts)
    sub = [None] * (1 << P); sub[0] = np.array([0], dtype=np.int64)
    tab = np.zeros(1 << P, dtype=np.int64)
    for S_ in range(1, 1 << P):
        i = (S_ & -S_).bit_length() - 1
        sub[S_] = Gr.plus_cyclic(sub[S_ ^ (1 << i)], pts[i])
        tab[S_] = round(math.log(len(sub[S_]), p))
    return tab


def table_min(f, n, tab, P, limit, rng):
    """minimum of f over configurations in which every variable is 0 or one of the P points (all (P+1)^n of them
    when that is at most `limit`, otherwise `limit` random ones).  Returns (min, count, all?)."""
    K = P + 1; total = K ** n
    if total <= limit:
        idx = np.arange(total, dtype=np.int64)
        digits = np.stack([(idx // K ** i) % K for i in range(n)], axis=1); full = True
    else:
        digits = rng.integers(0, K, size=(limit, n)); full = False
    bits = np.where(digits == 0, 0, np.left_shift(np.int64(1), np.maximum(digits - 1, 0)))
    vals = np.zeros(len(digits), dtype=np.int64)
    for X in range(1, 1 << n):
        if f[X]:
            u = np.zeros(len(digits), dtype=np.int64)
            for i in range(n):
                if X >> i & 1:
                    u |= bits[:, i]
            vals += f[X] * tab[u]
    return int(vals.min()), len(digits), full


def jmi_points(t, N, multipliers):
    """the J - I vectors e_i, c - e_i, c of Z_N^(t+1), each times every multiplier."""
    M = t + 1
    I = np.eye(M, dtype=np.int64); c = np.ones(M, dtype=np.int64)
    base = [I[i] for i in range(M)] + [c - I[i] for i in range(M)] + [c]
    return [(s * v) % N for s in multipliers for v in base]


def lemma_tests(limit, rng, log=print):
    """Lemma 4(G) on point configurations, plus the exact J - I values of the forms claimed only for other groups.
    Returns a list of (label, min, count, all?, claimed valid?)."""
    out = []
    specs = [  # (label, form t, which, N, point multipliers, claimed valid)
        ('(LA)_2 over Z_4^3', 2, 'LA', 4, (1,), False),
        ('(LB)_2 over Z_4^3', 2, 'LB', 4, (1,), False),
        ('(LB)_3 over Z_4^4', 3, 'LB', 4, (1, 2), True),
        ('(LA)_4 over Z_4^5', 4, 'LA', 4, (1,), True),
        ('(LB)_2 over Z_9^3', 2, 'LB', 9, (1, 3), True),
    ]
    for label, t, which, N, mult, valid in specs:
        LA, LB, n = g28.lemma_forms(t)
        f = LA if which == 'LA' else LB
        pts = jmi_points(t, N, mult)
        tab = point_table(Group(N, t + 1), pts)
        mn, cnt, full = table_min(f, n, tab, len(pts), limit, rng)
        out.append((label, mn, cnt, full, valid))
        log(f"  {label} [{'claimed valid' if valid else 'not claimed'}] on {'all' if full else 'random'} {cnt} "
            f"configurations of {len(pts)} points: min {mn}")
    for label, t, N in (('(LA)_3 on the J - I configuration over Z_4', 3, 4), ('(LA)_2 on the J - I configuration over Z_9', 2, 9)):
        LA, _LB, _n = g28.lemma_forms(t)
        v = int(LA @ rank_sum(g28.configuration(t), N))
        out.append((label, v, 1, True, False))
        log(f'  {label} [not claimed]: {v}')
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cases', nargs='+', default=[f'{t}:{N}' for t, N in CASES], help='t:N pairs')
    ap.add_argument('--state-vector', action='store_true')
    ap.add_argument('--lemma-tests', type=int, default=0, help='configurations per form (exhaustive if fewer exist)')
    ap.add_argument('--out', default=None)
    a = ap.parse_args()
    t0 = time.time()
    store = {}
    for cs in a.cases:
        t, N = map(int, cs.split(':'))
        W = analyse(t, N)
        unit = {2: 'bits', 3: 'trits'}.get(W['p'], f'log {W["p"]}')
        print(f"t = {t}, Z_{N} ({2 * t + 4} qudits, {W['n_visible']} visible parties + purifier, {unit}): free {W['free']}, "
              f"weights {W['weights']}, identically self-dual {W['self_dual']}, h_S == 2r {W['h2r']}, contraction == "
              f"configuration {W['contraction']}; configuration H(C) = {W['cfg'][1 << (2 * t + 2)]}, "
              f"H(B) = {W['cfg'][sum(1 << (t + 1 + i) for i in range(t + 1))]}, LA {W['cfg_LA']}, LB {W['cfg_LB']}; "
              f"pulled back on the state LA {W['FA']}, LB {W['FB']}  ({time.time() - t0:.0f}s)", flush=True)
        store[f't{t}_N{N}'] = W['S'].astype(np.int8)
    if a.state_vector:
        dev, size = state_vector_dev(2, 4)
        print(f'Z_4 cube state: |C| = {size}; max |S_svd - S_formula| over all 254 cuts = {dev:.1e} bits', flush=True)
        print(f'Z_4 cube entropy (bits) == qubit cube (bits) + qutrit cube (trits): {cube_sum_identity()}', flush=True)
    if a.lemma_tests:
        lemma_tests(a.lemma_tests, np.random.default_rng(29))
    if a.out:
        np.savez_compressed(a.out, cases=np.array([list(map(int, c.split(':'))) for c in a.cases]), **store)
        print('wrote', a.out)
    print(f'({time.time() - t0:.0f}s)')


if __name__ == '__main__':
    main()
